services:
  backend:
    image: ${NCP_REGISTRY_ENDPOINT}/${BACKEND_IMAGE}
    env_file:
      - .env
    container_name: web15-ipconfig-backend

    networks:
      - app-network
    environment:
      - NODE_ENV=production
      - HOST_URL=${HOST_URL}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - USE_REDIS_EXTENSION=${USE_REDIS_EXTENSION}
    volumes:
      - /var/log/web15-ipconfig:/app/logs
    restart: unless-stopped

  frontend:
    image: ${NCP_REGISTRY_ENDPOINT}/${FRONTEND_IMAGE}
    container_name: web15-ipconfig-frontend
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/certbot:/var/www/certbot
    networks:
      - app-network
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
